require("plugins")

require("core.options")
require("core.keymaps")

require("plugins.gruvbox")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
