require("plugins")

require("core.options")
require("core.keymaps")

require("plugins.gruvbox-baby")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.alpha")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.prettier")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.colorizer")
require("plugins.zen-mode")
